# Generated by Django 5.1.1 on 2024-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('goal_weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('goal_to_lose_weight', models.BooleanField(default=False)),
                ('goal_to_feel_better', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('google_acct_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
