# Generated by Django 5.1.1 on 2024-10-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_goal_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goal_type', models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Feel Better', 'Feel Better'), ('Both', 'Both')], max_length=20)),
                ('weight_value', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('feel_better_value', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
