# Generated by Django 5.1.1 on 2024-10-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
