# Generated by Django 5.1.1 on 2024-10-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
