# Generated by Django 5.1.1 on 2024-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='goal_type',
            field=models.CharField(choices=[('loseWeight', 'Lose Weight'), ('feelBetter', 'Feel Better'), ('both', 'Both')], max_length=20),
        ),
    ]
