# Generated by Django 5.1.1 on 2024-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userdata_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
