// These come from https://apinext.collegefootballdata.com/teams?year=2024

export const Abbreviations: {[key: string]: string} = {
    'Abilene Christian': 'ACU',
    'Adams State': 'ADST',
    'Adrian': 'ADR',
    'Air Force': 'AFA',
    'Akron': 'AKR',
    'Alabama': 'ALA',
    'Alabama A&M': 'AAMU',
    'Alabama State': 'ALST',
    'Albany State GA': 'ALBS',
    'Albion': 'ALBI',
    'Albright': 'ALB',
    'Alcorn State': 'ALCN',
    'Alderson-Broaddus': 'ABC',
    'Alfred State': 'ASC',
    'Alfred University': 'ALF',
    'Allegheny': 'ALL',
    'Allen': 'ALL',
    'Alma': 'ALM',
    'American International': 'AIC',
    'Amherst': 'AMH',
    'Anderson (IN)': 'AND',
    'Anderson (Sc)': 'AND',
    'Angelo State': 'ANG',
    'Anna Maria College': 'ANN',
    'App State': 'APP',
    'Apprentice School': 'APPRE',
    'Arizona': 'ARIZ',
    'Arizona State': 'ASU',
    'Arkansas': 'ARK',
    'Arkansas State': 'ARST',
    'Arkansas Tech': 'ARKTECH',
    'Arkansas-Monticello': 'ARKMONT',
    'Arkansas-Pine Bluff': 'UAPB',
    'Army': 'ARMY',
    'Ashland': 'ASH',
    'Assumption': 'ASP',
    'Auburn': 'AUB',
    'Augsburg': 'AUG',
    'Augustana (IL)': 'AUGIL',
    'Augustana University (SD)': 'AUSD',
    'Aurora': 'AUR',
    'Austin': 'AUS',
    'Austin Peay': 'APSU',
    'Averett': 'AVE',
    'Azusa Pacific': 'AZU',
    'Baldwin Wallace': 'BAL',
    'Ball State': 'BALL',
    'Bates': 'BAT',
    'Baylor': 'BAY',
    'Belhaven': 'BELHA',
    'Beloit': 'BEL',
    'Bemidji State': 'BST',
    'Benedict College': 'BEN',
    'Benedictine University': 'BENILL',
    'Bentley': 'BENT',
    'Berry College': 'BER',
    'Bethany (WV)': 'BETHWV',
    'Bethel (MN)': 'BET',
    'Bethune-Cookman': 'BCU',
    'Biddeford': 'NWENG',
    'Birmingham-Southern': 'BIR',
    'Black Hills State': 'BHST',
    'Bloomsburg': 'BLMSB',
    'Bluefield State': 'BLU',
    'Bluffton': 'BLUFFTON',
    'Boise State': 'BOIS',
    'Boston College': 'BC',
    'Bowdoin': 'BOW',
    'Bowie State': 'BSU',
    'Bowling Green': 'BGSU',
    'Brevard College': 'BRE',
    'Bridgewater (VA)': 'BRVA',
    'Bridgewater State': 'BRST',
    'Brockport': 'BRO',
    'Brown': 'BRWN',
    'Bryant': 'BRY',
    'Bucknell': 'BUCK',
    'Buena Vista': 'BUENA',
    'Buffalo': 'BUF',
    'Buffalo State': 'BUF',
    'Butler': 'BUT',
    'BYU': 'BYU',
    'Cal Poly': 'CP',
    'California': 'CAL',
    'California Lutheran University': 'CALLUTH',
    'Calvin University': 'CAL',
    'Campbell': 'CAM',
    'Capital': 'CAPITAL',
    'Carleton': 'CARLETON',
    'Carnegie Mellon': 'CARNGMELL',
    'Carroll University (WI)': 'CAR',
    'Carson-Newman College': 'CAR',
    'Carthage': 'CARCWI',
    'Case Western Reserve': 'CSR',
    'Castleton': 'CAS',
    'Catawba': 'CAT',
    'Catholic': 'CATH',
    'CENTENARY': 'CEN',
    'Central Arkansas': 'CARK',
    'Central College': 'CNTCIA',
    'Central Connecticut': 'CCSU',
    'Central Michigan': 'CMU',
    'Central Missouri': 'CENM',
    'Central Oklahoma': 'CENO',
    'Central State (OH)': 'CEN',
    'Central Washington': 'CENTWASH',
    'Centre College Kentucky': 'CENTRE',
    'Chadron St': 'CHADRONST',
    'Chapman': 'CHA',
    'Charleston Southern': 'CHSO',
    'Charlotte': 'CLT',
    'Chattanooga': 'UTC',
    'Cheyney': 'CHE',
    'Chicago': 'CHI',
    'Chowan': 'CHOWA',
    'Christopher Newport': 'CHR',
    'Cincinnati': 'CIN',
    'Claremont-Mudd-Scripps College': 'CLA',
    'Clarion': 'CLARION',
    'Clark Atlanta': 'CLA',
    'Clemson': 'CLEM',
    'Coast Guard': 'USCGA',
    'Coastal Carolina': 'CCU',
    'Coe College': 'COE',
    'Colby College': 'COLBY',
    'Colgate': 'COLG',
    'College Of New Jersey': 'COL',
    'Colorado': 'COLO',
    'Colorado Mesa': 'MESA',
    'Colorado School Of Mines': 'COLOMINES',
    'Colorado State': 'CSU',
    'Columbia': 'COLU',
    'Concord University': 'CON',
    'Concordia Moorhead': 'CONCOMN',
    'Concordia University Chicago': 'CONCOIL',
    'Concordia University St Paul': 'CON',
    'Concordia-Wisconsin': 'CONW',
    'Cornell': 'COR',
    'Cornell College (IA)': 'CORNELLIA',
    'Cortland': 'CORTLAND',
    'Crown College': 'CROWN',
    'CSU Pueblo': 'CSTP',
    'Curry College': 'CUR',
    'Dartmouth': 'DART',
    'Davenport': 'DU',
    'Davidson': 'DAV',
    'Dayton': 'DAY',
    'Dean College': 'DEA',
    'Delaware': 'DEL',
    'Delaware State': 'DSU',
    'Delaware Valley': 'DV',
    'Delta State': 'DELTAST',
    'Denison University': 'DEN',
    'Depauw': 'DEP',
    'Dickinson (PA)': 'DIC',
    'Drake': 'DRKE',
    'Dubuque': 'DUB',
    'Duke': 'DUKE',
    'Duquesne': 'DUQ',
    'East Carolina': 'ECU',
    'East Central (OK)': 'EAS',
    'East Stroudsburg University': 'ESTROUD',
    'East Tennessee State': 'ETSU',
    'East Texas A&M': 'ETAM',
    'East Texas Baptist University': 'EAS',
    'Eastern Illinois': 'EIU',
    'Eastern Kentucky': 'EKU',
    'Eastern Michigan': 'EMU',
    'Eastern New Mexico': 'EASTERNNM',
    'Eastern University': 'EAS',
    'Eastern Washington': 'EWU',
    'Edinboro University': 'EDI',
    'Edward Waters': 'EDW',
    'Elizabeth City State': 'ELI',
    'Elmhurst': 'ELM',
    'Elon': 'ELON',
    'Emory & Henry College': 'EMHEN',
    'Emporia State University': 'EMP',
    'Endicott College': 'END',
    'ERSKINE': 'ERSKINE',
    'Eureka College': 'EUR',
    'Fairmont State': 'FAIRST',
    'Fayetteville State': 'FAY',
    'FDU-Florham': 'FDUFLOR',
    'Ferris State': 'FRST',
    'Ferrum': 'FER',
    'Findlay': 'FINDLAY',
    'Finlandia University': 'FINL',
    'Fitchburg State': 'FITCH',
    'Florida': 'FLA',
    'Florida A&M': 'FAMU',
    'Florida Atlantic': 'FAU',
    'Florida International': 'FIU',
    'Florida State': 'FSU',
    'Fordham': 'FOR',
    'Fort Hays State': 'FTHAYST',
    'Fort Lewis': 'FORTLEW',
    'Fort Valley State': 'FOR',
    'Framingham State': 'FRA',
    'Franklin': 'FRANKLIN',
    'Franklin & Marshall': 'FRKLNMAR',
    'Franklin Pierce': 'FRANK',
    'Fresno State': 'FRES',
    'Frostburg State': 'FRO',
    'Furman': 'FUR',
    'Gallaudet': 'GALLAUDET',
    'Gannon': 'GAN',
    'Gardner-Webb': 'GWEB',
    'Geneva': 'GENEVA',
    'Georgetown': 'GTWN',
    'Georgia': 'UGA',
    'Georgia Southern': 'GASO',
    'Georgia State': 'GAST',
    'Georgia Tech': 'GT',
    'Gettysburg': 'GETTY',
    'Glenville State': 'GLENVILLE',
    'Grambling': 'GRAM',
    'Grand Valley State University': 'GVSU',
    'Greeneville': 'TUS',
    'Greensboro College': 'GRNSBORO',
    'Greenville': 'GRNVIL',
    'Grinnell': 'GRI',
    'Grove City College': 'GRO',
    'Guilford College': 'GUI',
    'Gustavus Adolphus': 'GUSADOL',
    'Hamilton': 'HAM',
    'Hamline University': 'HAM',
    'Hampden-Sydney': 'HAM',
    'Hampton': 'HAMP',
    'Hanover College': 'HAN',
    'Harding University': 'HARDING',
    'Hardin-Simmons': 'HARDSIM',
    'Hartwick': 'HAR',
    'Harvard': 'HARV',
    'Hawai\'i': 'HAW',
    'Heidelberg': 'HEI',
    'Henderson State': 'HENDERSON',
    'Hendrix College': 'HENDRIX',
    'Hilbert College': 'HIL',
    'Hillsdale': 'HILLSDALE',
    'Hiram College': 'HIRAM',
    'Hobart College': 'HBRT',
    'Holy Cross': 'HC',
    'Hope College': 'HOP',
    'Houston': 'HOU',
    'Houston Christian': 'HCU',
    'Howard': 'HOW',
    'Howard Payne': 'HOWPAY',
    'Huntingdon College (AL)': 'HNTNGDN',
    'Husson': 'HUSSON',
    'Idaho': 'IDHO',
    'Idaho State': 'IDST',
    'Illinois': 'ILL',
    'Illinois College': 'ILLCOLL',
    'Illinois State': 'ILST',
    'Illinois Wesleyan': 'ILLWES',
    'Incarnate Word': 'UIW',
    'Indiana': 'IU',
    'Indiana State': 'INST',
    'Indiana-Pennsylvania': 'INDIANAPA',
    'Indianapolis': 'INDY',
    'Iowa': 'IOWA',
    'Iowa State': 'ISU',
    'Ithaca College': 'ITH',
    'Jackson State': 'JKST',
    'Jacksonville State': 'JVST',
    'James Madison': 'JMU',
    'John Carroll University': 'JOH',
    'Johns Hopkins University': 'JHU',
    'Johnson C Smith': 'JOH',
    'Juniata College': 'JUN',
    'Kalamazoo': 'KAL',
    'Kansas': 'KU',
    'Kansas State': 'KSU',
    'Kean': 'KEAN',
    'Kennesaw State': 'KENN',
    'Kent State': 'KENT',
    'Kentucky': 'UK',
    'Kentucky State': 'KYST',
    'Kentucky Wesleyan': 'KYWESL',
    'Kenyon': 'KEN',
    'Keystone': 'KEYST',
    'Kings College (PA)': 'KIN',
    'Knox College': 'KNO',
    'Kutztown University': 'KUTZTOWN',
    'La Verne': 'LAVERNE',
    'Lafayette': 'LAF',
    'Lagrange College': 'LAG',
    'Lake Erie': 'LAKEERIE',
    'Lake Forest College': 'LAK',
    'Lakeland': 'LAKEL',
    'Lamar': 'LAM',
    'Lane College': 'LAC',
    'Lawrence University': 'LAW',
    'Lebanon Valley': 'LEB',
    'Lehigh': 'LEH',
    'Lenoir-Rhyne': 'LENRHYNE',
    'Lewis & Clark College': 'LEW',
    'Liberty': 'LIB',
    'Limestone': 'LIMESTONE',
    'Lincoln (CA)': 'LIN',
    'Lincoln (MO)': 'LIN',
    'Lincoln (PA)': 'LINP',
    'Lindenwood': 'LIN',
    'Linfield College': 'LIN',
    'Livingstone': 'LIV',
    'Lock Haven University': 'LHU',
    'Long Island University': 'LIU',
    'Loras College': 'LOR',
    'Louisiana': 'UL',
    'Louisiana Tech': 'LT',
    'Louisville': 'LOU',
    'LSU': 'LSU',
    'Luther': 'LUT',
    'Lycoming': 'LYCOMING',
    'LYONCOLL': 'LYON',
    'Macalester': 'MACALES',
    'Maine': 'ME',
    'Maine Maritime': 'MAI',
    'Manchester': 'MNCHSTR',
    'Marietta': 'MAR',
    'Marist': 'MRST',
    'Mars Hill': 'MARSHILL',
    'Marshall': 'MRSH',
    'Martin Luther': 'MAR',
    'Mary Hardin-Baylor': 'MRYHRBAY',
    'Maryland': 'MD',
    'Maryville College (TN)': 'MRYVILTN',
    'Mass Maritime': 'MAMARI',
    'Massachusetts': 'MASS',
    'McDaniel College': 'MCD',
    'McKendree': 'MAN',
    'McMurry': 'MCM',
    'McNeese': 'MCN',
    'Memphis': 'MEM',
    'Mercer': 'MER',
    'Merchant Marine Academy': 'MER',
    'Mercyhurst': 'MERC',
    'Merrimack': 'MRMK',
    'Methodist': 'MTH',
    'Miami': 'MIA',
    'Miami (OH)': 'M-OH',
    'Michigan': 'MICH',
    'Michigan State': 'MSU',
    'Michigan Tech': 'MTU',
    'Middle Tennessee': 'MTSU',
    'Middlebury': 'MIDLBRY',
    'Midwestern State': 'MID',
    'Miles College': 'MIL',
    'Millersville': 'MIL',
    'Millikin': 'MIL',
    'Millsaps': 'MIL',
    'Minnesota': 'MINN',
    'Minnesota Duluth': 'UMD',
    'Minnesota Morris': 'MNMOR',
    'Minnesota State Mankato': 'MNST',
    'Minnesota State Moorhead': 'MIN',
    'Minot State': 'MIN',
    'Misericordia': 'MISC',
    'Mississippi College': 'MIS',
    'Mississippi State': 'MSST',
    'Mississippi Valley State': 'MVSU',
    'Missouri': 'MIZ',
    'Missouri S&T': 'MISSO',
    'Missouri Southern State': 'MOSSTC',
    'Missouri State': 'MOST',
    'Missouri Western': 'MOW',
    'MIT': 'MIT',
    'Monmouth': 'MONM',
    'Monmouth (IL)': 'MONMIL',
    'Montana': 'MONT',
    'Montana State': 'MTST',
    'Montclair State': 'MON',
    'Moravian': 'MOR',
    'Morehead State': 'MORE',
    'Morehouse College': 'MOR',
    'Morgan State': 'MORG',
    'Mount Ida College': 'MOU',
    'Mount St. Joseph': 'MTS',
    'Muhlenberg': 'MHLBRG',
    'Murray State': 'MUR',
    'Muskingum University': 'MUS',
    'Navy': 'NAVY',
    'NC State': 'NCSU',
    'Nebraska': 'NEB',
    'Nebraska Wesleyan': 'NEBWS',
    'Nebraska-Kearney': 'NEKR',
    'Nevada': 'NEV',
    'New Hampshire': 'UNH',
    'New Haven': 'NH',
    'New Mexico': 'UNM',
    'New Mexico Highlands': 'NMH',
    'New Mexico State': 'NMSU',
    'NEWBERG': 'GFU',
    'Newberry': 'NBY',
    'Nicholls': 'NICH',
    'Nichols College': 'NICHOLS',
    'Norfolk State': 'NORF',
    'North Alabama': 'UNA',
    'North Carolina': 'UNC',
    'North Carolina A&T': 'NCAT',
    'North Carolina Central': 'NCCU',
    'North Carolina Wesleyan': 'NORTH',
    'North Central College': 'NOR',
    'North Dakota': 'UND',
    'North Dakota State': 'NDSU',
    'North Greenville': 'NG',
    'North Park': 'NOR',
    'North Texas': 'UNT',
    'Northeastern State': 'NOR',
    'Northern Arizona': 'NAU',
    'Northern Colorado': 'UNCO',
    'Northern Illinois': 'NIU',
    'Northern Iowa': 'UNI',
    'Northern Michigan': 'NMI',
    'Northern State': 'NOR',
    'Northwest Missouri St': 'NWMS',
    'Northwestern': 'NU',
    'Northwestern (MN)': 'NWMN',
    'Northwestern Oklahoma State': 'NWO',
    'Northwestern State': 'NWST',
    'Northwood (MI)': 'NAR',
    'Norwich': 'NOR',
    'Notre Dame': 'ND',
    'Notre Dame College': 'NOT',
    'Oberlin': 'OBERLIN',
    'Occidental': 'OCC',
    'Ohio': 'OHIO',
    'Ohio Dominican': 'ull,',
    'Ohio Northern': 'OHNRTH',
    'Ohio State': 'OSU',
    'Ohio Wesleyan': 'OHWESL',
    'Oklahoma': 'OU',
    'Oklahoma Baptist': 'OB',
    'Oklahoma Panhandle St': 'OKLAH',
    'Oklahoma State': 'OKST',
    'Old Dominion': 'ODU',
    'Ole Miss': 'MISS',
    'Olivet College': 'OLI',
    'Oregon': 'ORE',
    'Oregon State': 'ORST',
    'Otterbein': 'OTT',
    'Ouachita Baptist': 'OUA',
    'Pace': 'PAC',
    'Pacific (OR)': 'PAC',
    'Pacific Lutheran': 'PACLTH',
    'Penn State': 'PSU',
    'Pennsylvania': 'PENN',
    'PennWest California': 'PWC',
    'Pittsburg St': 'PIT',
    'Pittsburgh': 'PITT',
    'Plymouth State': 'PLYST',
    'Pomona Pitzer': 'POM',
    'Portland State': 'PRST',
    'Post University': 'POS',
    'Prairie View A&M': 'PV',
    'Presbyterian': 'PRES',
    'Princeton': 'PRIN',
    'Puget Sound': 'PUGET',
    'Purdue': 'PUR',
    'Quincy': 'QUI',
    'Randolph-Macon': 'RAN',
    'Reading': 'ALVERNIA',
    'Redlands': 'RED',
    'Rensselaer': 'RPI',
    'Rhode Island': 'URI',
    'Rhodes College': 'RHO',
    'Rice': 'RICE',
    'Richmond': 'RICH',
    'Ripon': 'RIP',
    'Robert Morris': 'RMU',
    'Rockford': 'ROCKF',
    'Roosevelt': 'ROO',
    'Rose-Hulman': 'ROSEHUL',
    'Rowan': 'ROW',
    'Rutgers': 'RUTG',
    'Sacramento State': 'SAC',
    'Sacred Heart': 'SHU',
    'Saginaw Valley State': 'SAGI',
    'Saint John\'s (MN)': 'ST. J',
    'Saint Vincent': 'STV',
    'Salisbury': 'SALIS',
    'Salve Regina': 'SALVE',
    'Sam Houston': 'SHSU',
    'Samford': 'SAM',
    'San Diego': 'USD',
    'San Diego State': 'SDSU',
    'San José State': 'SJSU',
    'Savannah St': 'SAV',
    'SE Louisiana': 'SELA',
    'Seton Hill': 'SETONHILL',
    'Sewanee': 'SEWAN',
    'Shaw': 'SHAW',
    'Shenandoah': 'SHENAN',
    'Shepherd': 'SHE',
    'Shippensburg': 'SHPSBRG',
    'Shorter': 'SHOR',
    'Simon Fraser': 'SIM',
    'Simpson College (IA)': 'SIMPS',
    'Sioux Falls': 'SIO',
    'Slippery Rock': 'SRU',
    'SMU': 'SMU',
    'South Alabama': 'USA',
    'South Carolina': 'SC',
    'South Carolina State': 'SCST',
    'South Dakota': 'SDAK',
    'South Dakota Mines': 'SDMT',
    'South Dakota State': 'SDST',
    'South Florida': 'USF',
    'Southeast Missouri State': 'SEMO',
    'Southeastern Oklahoma State': 'SEOS',
    'Southern': 'SOU',
    'Southern Arkansas': 'SOU',
    'Southern Connecticut State': 'SOU',
    'Southern Illinois': 'SIU',
    'Southern Miss': 'USM',
    'Southern Nazarene': 'STN',
    'Southern Utah': 'SUU',
    'Southern Virginia': 'SVA',
    'Southwest Baptist': 'SWB',
    'Southwest Minnesota State': 'SWMN',
    'Southwestern Oklahoma State': 'SWO',
    'Southwestern University': 'SW',
    'Springfield': 'SPR',
    'St John Fisher University': 'SJFISH',
    'St. Anselm': 'STA',
    'St. Augustine\'s': 'STA',
    'St. Francis (PA)': 'SFPA',
    'St. Joseph\'s (IN)': 'ST',
    'St. Lawrence': 'USL',
    'St. Norbert': 'STN',
    'St. Olaf': 'STO',
    'St. Scholastica': 'SCHOLA',
    'St. Thomas (MN)': 'STMN',
    'Stanford': 'STAN',
    'Stephen F. Austin': 'SFA',
    'Stetson': 'STET',
    'Stevenson': 'STU',
    'Stonehill': 'STO',
    'Stony Brook': 'STBK',
    'Sul Ross State': 'SROS',
    'SUNY Maritime': 'SUNYMAR',
    'SUNY Morrisville': 'MOR',
    'Susquehanna': 'SUS',
    'Syracuse': 'SYR',
    'Tarleton State': 'TAR',
    'TCU': 'TCU',
    'Temple': 'TEM',
    'Tennessee': 'TENN',
    'Tennessee State': 'TNST',
    'Tennessee Tech': 'TNTC',
    'Texas': 'TEX',
    'Texas A&M': 'TA&M',
    'Texas A&M-Kingsville': 'TXA',
    'Texas Lutheran': 'TL',
    'Texas Southern': 'TXSO',
    'Texas State': 'TXST',
    'Texas Tech': 'TTU',
    'The Citadel': 'CIT',
    'Thiel': 'THIEL',
    'Thomas More College': 'THMORE',
    'Tiffin': 'TIF',
    'Tiffin University': 'TIF',
    'Toledo': 'TOL',
    'Towson': 'TOW',
    'Trine University': 'TRI',
    'Trinity (CT)': 'TRI',
    'Trinity University TX': 'TRTX',
    'Troy': 'TROY',
    'Truman State': 'TRU',
    'Tufts': 'TUF',
    'Tulane': 'TULN',
    'Tulsa': 'TLSA',
    'Tuskegee': 'TUS',
    'UAB': 'UAB',
    'UAlbany': 'ALB',
    'UC Davis': 'UCD',
    'UCF': 'UCF',
    'UCLA': 'UCLA',
    'UConn': 'CONN',
    'UL Monroe': 'ULM',
    'UMass Dartmouth': 'MASSA',
    'UNC Pembroke': 'NCPEMB',
    'Union (NY)': 'UNNY',
    'University Of Charleston (WV)': 'CHWV',
    'University of Mary': 'MARY',
    'University of Mount Union': 'MTU',
    'University of Rochester (NY)': 'ROC',
    'UNLV': 'UNLV',
    'Upper Iowa University': 'UPPERIOWA',
    'Ursinus': 'URS',
    'USC': 'USC',
    'UT Martin': 'UTM',
    'UT Permian Basin': 'TXPBAS',
    'Utah': 'UTAH',
    'Utah State': 'USU',
    'Utah Tech': 'UTU',
    'UTEP': 'UTEP',
    'Utica': 'UTICA',
    'UTSA': 'UTSA',
    'UVA Wise': 'VIRWISE',
    'Valdosta State': 'VAL',
    'Valparaiso': 'VAL',
    'Vanderbilt': 'VAN',
    'Villanova': 'VILL',
    'Virginia': 'UVA',
    'Virginia St': 'VIR',
    'Virginia Tech': 'VT',
    'Virginia Union': 'VU',
    'VMI': 'VMI',
    'Wabash College': 'WAB',
    'Wagner': 'WAG',
    'Wake Forest': 'WAKE',
    'Walsh': 'WAL',
    'Wartburg': 'WAR',
    'Washburn': 'WAS',
    'Washington': 'WASH',
    'Washington & Jefferson': 'WAS',
    'Washington and Lee': 'UWL',
    'Washington State': 'WSU',
    'Washington University (St. Louis)': 'WSTL',
    'Wayne State (MI)': 'WAY',
    'Wayne State (NE)': 'WNST',
    'Waynesburg': 'WAYNEB',
    'Weber State': 'WEB',
    'Wesleyan University (CT)': 'WES',
    'West Alabama': 'WES',
    'West Chester': 'WES',
    'West Florida': 'WES',
    'West Georgia': 'WGA',
    'West Liberty': 'WLIBST',
    'West Texas A&M': 'WES',
    'West Virginia': 'WVU',
    'West Virginia State': 'WEST ',
    'West Virginia Wesleyan': 'WEST',
    'Western Carolina': 'WCU',
    'Western Colorado': 'WESTSTCOL',
    'Western Connecticut St': 'WES',
    'Western Illinois': 'WIU',
    'Western Kentucky': 'WKU',
    'Western Michigan': 'WMU',
    'Western New England': 'WNWENG',
    'Western New Mexico': 'WNMEX',
    'Western Oregon': 'WORE',
    'Westfield State': 'WES',
    'Westminster (PA)': 'WMNPA',
    'Westminster College (MO)': 'WMN',
    'Wheaton': 'WHEATON',
    'Wheeling': 'WHEEL',
    'Whittier': 'WHI',
    'Whitworth': 'WHI',
    'Widener': 'WID',
    'Wilkes': 'WILKES',
    'Willamette': 'WLLMTT',
    'William & Mary': 'W&M',
    'William Jewell': 'WILLI',
    'William Paterson': 'WILLPAT',
    'Williams': 'WIL',
    'Wilmington (OH)': 'WILMOH',
    'Wilson': 'BARTON',
    'Wingate': 'WIN',
    'Winona State': 'WIN',
    'Winston-Salem': 'WNSL',
    'Wisconsin': 'WIS',
    'Wisconsin-Eau Claire': 'WISE',
    'Wisconsin-Lacrosse': 'WISL',
    'Wisconsin-Lutheran': 'WILU',
    'Wisconsin-Oshkosh': 'WISO',
    'Wisconsin-Platteville': 'WIPL',
    'Wisconsin-River Falls': 'WIRF',
    'Wisconsin-Stevens Pt': 'WISP',
    'Wisconsin-Stout': 'WISS',
    'Wisconsin-Whitewater': 'WISW',
    'Wittenberg': 'WITTEN',
    'Wofford': 'WOF',
    'Wooster': 'WOO',
    'Worcester Polytechnic Institute': 'WORCE',
    'Worcester St': 'WORST',
    'Wyoming': 'WYO',
    'Yale': 'YALE',
    'Youngstown State': 'YSU',
};